version: '3'

services:
    
    proxy:
        restart: unless-stopped
        build:
            context: ./proxy/
        ports:
            - 80:80
        depends_on:
            - registry

    registry:
        restart: unless-stopped
        image: registry
        environment:
            - REGISTRY_HTTP_ADDR=0.0.0.0:80
    
    
